import re
from typing import Any, List, Optional
from pydantic import BaseModel, Field, model_validator


# ---------------------------------------------------------------------------
# Career Analysis Response Schema
# ---------------------------------------------------------------------------

class RecommendedCareer(BaseModel):
    career_id: Optional[str] = None
    title: str
    score: float = Field(..., ge=0.0, le=100.0)
    
    # 5-Dimension Match Analysis
    branch_compatibility: float = Field(default=85.0, ge=0.0, le=100.0)
    skill_match: float = Field(default=80.0, ge=0.0, le=100.0)
    interest_alignment: float = Field(default=85.0, ge=0.0, le=100.0)
    goal_alignment: float = Field(default=80.0, ge=0.0, le=100.0)
    academic_compatibility: float = Field(default=85.0, ge=0.0, le=100.0)

    reason: str
    matched_skills: List[str] = Field(default_factory=list)
    missing_skills: List[str] = Field(default_factory=list)
    career_outlook: Optional[str] = None
    next_steps: List[str] = Field(default_factory=list)

    @model_validator(mode="before")
    @classmethod
    def normalize_fields(cls, data: Any) -> Any:
        if isinstance(data, dict):
            # Map career_title -> title
            if "career_title" in data and "title" not in data:
                data["title"] = data["career_title"]
            # Map compatibility_score -> score
            if "compatibility_score" in data and "score" not in data:
                data["score"] = data["compatibility_score"]
            # Auto-generate career_id if missing
            if not data.get("career_id") and data.get("title"):
                data["career_id"] = re.sub(r"[^a-zA-Z0-9]+", "-", str(data["title"]).strip().lower()).strip("-")
            # Map required_skills -> matched_skills if matched_skills missing
            if "required_skills" in data and not data.get("matched_skills"):
                data["matched_skills"] = data["required_skills"]
            # Map skill_gaps list of strings if present
            if "skill_gaps" in data and not data.get("missing_skills") and isinstance(data["skill_gaps"], list):
                data["missing_skills"] = [
                    s if isinstance(s, str) else s.get("skill_name", "")
                    for s in data["skill_gaps"]
                ]
        return data


class SkillGapItem(BaseModel):
    skill_name: str
    current_level: Optional[str] = None   # beginner/intermediate/advanced/none
    required_level: str
    priority: str  # high / medium / low
    learning_resource: Optional[str] = None


class RoadmapStepItem(BaseModel):
    step_number: int = Field(..., ge=1)
    title: str
    description: str
    duration_weeks: Optional[int] = Field(None, ge=1, le=52)
    skills_gained: List[str] = Field(default_factory=list)
    resources: List[str] = Field(default_factory=list)


class ProjectRecommendation(BaseModel):
    title: str
    description: str
    skills_practiced: List[str] = Field(default_factory=list)
    difficulty: str  # beginner / intermediate / advanced
    estimated_hours: Optional[int] = None


class CareerAnalysisAIResponse(BaseModel):
    """
    Pydantic schema for the complete structured JSON returned by Gemini
    in a single career analysis call.
    """
    summary: str = Field(..., min_length=20)
    recommended_careers: List[RecommendedCareer] = Field(..., min_length=1, max_length=10)
    strengths: List[str] = Field(default_factory=list)
    skill_gaps: List[SkillGapItem] = Field(default_factory=list)
    priority_skills: List[str] = Field(default_factory=list)
    roadmap_steps: List[RoadmapStepItem] = Field(default_factory=list)
    project_recommendations: List[ProjectRecommendation] = Field(default_factory=list)
    next_steps: List[str] = Field(default_factory=list)

    @model_validator(mode="before")
    @classmethod
    def normalize_response(cls, data: Any) -> Any:
        if isinstance(data, dict):
            if "overall_summary" in data and "summary" not in data:
                data["summary"] = data["overall_summary"]
        return data


class RoleRoadmapAIResponse(BaseModel):
    """
    Pydantic schema for role-specific roadmap generated by Gemini
    specifically for the student's selected career role.
    """
    career_target: str
    roadmap_steps: List[RoadmapStepItem] = Field(..., min_length=1)
    project_recommendations: List[ProjectRecommendation] = Field(default_factory=list)
    skill_gaps: List[SkillGapItem] = Field(default_factory=list)
    priority_skills: List[str] = Field(default_factory=list)

    @model_validator(mode="before")
    @classmethod
    def normalize_role_roadmap(cls, data: Any) -> Any:
        if isinstance(data, dict):
            if "target_career" in data and "career_target" not in data:
                data["career_target"] = data["target_career"]
            if "career_title" in data and "career_target" not in data:
                data["career_target"] = data["career_title"]
        return data


# ---------------------------------------------------------------------------
# Resume Analysis Response Schema
# ---------------------------------------------------------------------------

class ResumeAnalysisAIResponse(BaseModel):
    """
    Pydantic schema for Gemini's resume feedback.
    guidance_score is a career guidance readiness score (0-100),
    NOT an employer hiring score.
    """
    guidance_score: int = Field(..., ge=0, le=100)
    strengths: List[str] = Field(default_factory=list)
    missing_skills: List[str] = Field(default_factory=list)
    formatting_feedback: List[str] = Field(default_factory=list)
    project_suggestions: List[str] = Field(default_factory=list)
    skill_alignment: str = Field(..., min_length=10)
    improvement_suggestions: List[str] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Chatbot (no structured schema required — plain text response)
# ---------------------------------------------------------------------------
